sudo: required
services:
  - docker

before_install:
  - docker build -t t4christ/react-docker -f ./docker-react/Dockerfile.dev ./docker-react

script:
  - docker run t4christ/react-docker npm run test -- --coverage

after_success:
  - docker build -t texplode/client  ./docker-react
  - docker build -t texplode/nginx  ./nginx
  - docker build -t texplode/server  ./server
  - docker build -t texplode/worker  ./worker

# Login to Docker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


# Take images and push them to dockerhub

  - docker push texplode/client
  - docker push texplode/nginx
  - docker push texplode/worker
  - docker push texplode/server


# deploy:
#   provider: elasticbeanstalk
#   region: us-east-2
#   app: mulit-docker
#   env: MulitDocker-env
#   bucket_name: elasticbeanstalk-us-east-2-632874205370
#   bucket_path: docker-react
#   on:
#     branch: master

#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"